name: mad_final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  intl: ^0.19.0
  lottie: ^3.1.0
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Images/
